Feat/implementacao alerta resub #1
jlcarvalho/bot-da-live pull request #10
Opened 2022-01-14 21:48 UTC by Limatucano

Implementação da funcionalidade de escutar o evento de resub no canal.

Eu acredito que essa não seja a melhor forma de ser feita, podemos agrupar os eventos em um object e acessar pela propriedade, já que o comportamento a principio é o mesmo ou colocar dentro de uma function recebendo alguns params como valor de opacidade e time.

Mas o que você acha?

2022-01-19 00:29 UTC, jlcarvalho requested changes
Primeiramente eu gostaria de agradecer por você ter submetido o PR, fiquei realmente surpreso e feliz quando vi ele aqui. Obrigado 😄 

Eu fiz algumas sugestões no código, algumas relacionadas a bugs e outras relacionadas a melhorias de legibilidade mesmo, assim que você ajustar eu faço o merge aqui.

2022-01-19 00:29 UTC, jlcarvalho commented on assets/alerts.html
> +      monthEl.innerText = msg.months
Acho que ficou invertido a atualização dos meses, né?

Essa linha deveria estar no listener de `resub`.

2022-01-19 00:29 UTC, jlcarvalho commented on assets/alerts.html
> +    var monthEl = document.querySelector(".months");
Ia ser legal essa variável `monthEl` ter um nome que deixe mais claro o que ela faz, que que você acha de `streakMonths`?

2022-01-19 00:29 UTC, jlcarvalho commented on assets/alerts.html
> +        });
Ia ser legal se a gente abstraísse essa lógica aqui também.

Algo tipo:

```js
function animateBox(el) {
  window.requestAnimationFrame(function() {
    el.style.opacity = '1';

    setTimeout(() => {
      el.style.opacity = '0';
    }, 8000);
  });
}
```

Assim conseguiríamos reaproveitar ela tanto pro `subscriptionBox` quanto para o `resubBox`.

```js
animateBox(subscriptionBox);
animateBox(resubBox);
```

Faz sentido?

2022-01-19 00:29 UTC, jlcarvalho commented on assets/alerts.html
> +    Obrigado pelo resub de <b class="months"></b> mes(es) <b class="username"></b>
Seria legal colocar `streakMonths` aqui também e acho que como é resub, nunca vai ser `mes`, sempre serão `meses`.

```suggestion
    Obrigado pelo resub de <b class="streakMonths"></b> meses <b class="username"></b>
```

2022-01-19 00:29 UTC, jlcarvalho commented on assets/alerts.html
> +      usernameEl.innerText = msg.username;
Por ter reaproveitado o elemento `usernameEl` aqui, o navegador vai selecionar sempre a primeira, que é a que está dentro de `subscriptionBox`. Talvez seja melhor separar a seleção desses elementos (a classe até pode continuar igual). Exemplo:

```js 
var subscriptionBox = document.querySelector("#subscriptionBox");
var resubBox = document.querySelector("#resubBox");

socket.on('subscription', function(msg) {
  var usernameEl = subscriptionBox.querySelector(".username");
});

socket.on('resub', function(msg) {
  var usernameEl = resubBox.querySelector(".username");
});
```

2022-01-19 09:53 UTC, Limatucano commented
cara, que legal. Eu nunca tive essa interação de code review, sempre trabalhei sozinho kkkk então estou bem animado. 
Vou dar uma olhada nos pontos que vc comentou, ai preciso abrir um novo PR? Ou tem como atrelar um commit aqui?

2022-01-19 11:50 UTC, Limatucano commented
acho que consegui fazer o commit, se nao conseguir ver me da um alo.
Sobre as mudanças que sugeriu achei ótimas, na função animateBox eu adicionei um param para duraçao do box, caso a gente precise que algum seja mais rapido ou algo do tipo, mas o default está 8000

2022-01-20 00:26 UTC, jlcarvalho commented
@Limatucano show de bola cara, amanhã na live eu faço o review novamente, pode ser?

2022-01-20 01:45 UTC, Limatucano commented
beleza @jlcarvalho. Vou ficar ligado no twitter para saber da live, mas tem ideia de que horas vai começar?

2022-01-20 03:06 UTC, jlcarvalho commented
@Limatucano toda terça, quinta e sábado às 19h.

2022-01-20 22:27 UTC, jlcarvalho approved these changes
![image](https://user-images.githubusercontent.com/1238663/150432186-cdc4f21b-cba9-48d5-9932-8c29e4ebff93.png)

2022-01-20 22:28 UTC, merged